services:
  postgres_service:
    image: postgres:17.10-alpine3.24
    container_name: postgres
    env_file:
    - .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - invoice_app_net
    ports:
      - 8080:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker_user -d invoice_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  invoice_app_service:
    build: .
    image: invoice_app_image
    container_name: invoice_app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - invoice_app_net
    # ports:
    #   - 8000:8000
    env_file:
      - .env.docker
    depends_on:
      postgres_service:
        condition: service_healthy
  
  nginx_service:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/invoice_ai/app/static:ro  # статика напрямую
    networks:
      - invoice_app_net
    depends_on:
      - invoice_app_service

networks:
  invoice_app_net:
    driver: bridge

volumes:
  postgres-data: